### ISSUE TITLE
Use standard Open Source license

### ISSUE THREAD

**Issue by cruftex** [ColonelBlimp/Mellifluous#3]
There is no license in the project root directory, but the header of the Java files have a license text.

The license text is non standard. This makes it difficult for any body to asses whether the needed rights are granted to use the project.

I recommend to use an OSI approved license. Take a look at:
https://opensource.com/law/13/1/which-open-source-software-license-should-i-use

**Comment by ColonelBlimp** [comment]
Hi Jens,

Many thanks for the feedback.  I'll get the changes done later today.  I 
also noticed a local filepath reference in the pom.xml, which I will 
also remove.

Again, many thanks for the useful feedback.

I wish you a happy and prosperous New Year.
--
Marc

------ Original Message ------
